myweb/mysite/myapp/urls.py
from django.urls import path, re_path
from . import views
from .views import DetailList, CreateWebpage, ListV, Base, Cap, Update, DeleteV
from .models import Webpage
app_name = 'myapp'

urlpatterns = [
    path('create/', CreateWebpage.as_view(), name='cwp'),
    path('list/', ListV.as_view(), name='list'),
    path('myapp/cap/', Cap.as_view(), name='cap'),
    path('myapp/base/', Base.as_view(), name='base'),
    path('detail/<pk>', DetailList.as_view(), name='detail'),
    path('delete/<pk>', DeleteV.as_view(), name='delete'),
    path('update/<pk>', Update.as_view(), name='update'),
    #path(r'^(?P<wepdetail_id>\d+)/share/$', views.wepdetail_share,
    # name='wepdetail_share'),
]

myweb/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', views.index, name='index'),
    path('myapp/', include("myapp.urls"), name='myapp'),
    path('admin/', admin.site.urls)
]
urlpatterns += staticfiles_urlpatterns()

myweb/mysite/myapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    name = models.CharField(max_length=264, unique=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, blank=True, related_name='webpage')
    url = models.URLField(unique=True)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("myapp:detail", kwargs={"pk": self.pk})

    def get_success_url(self):
        return reverse_lazy('myapp:detail')

class AcessRecord(models.Model):
    date = models.DateField()
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.date)

myweb/mysite/myapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.urls import reverse
from .models import Webpage, Topic
from django.views.generic import (TemplateView, ListView, DetailView, CreateView,
                                  UpdateView, DeleteView)

# Create your views here
def index(request):
    return render(request, 'index.html')

class DetailList(DetailView):
    model = Webpage
    template_name = 'myapp/webpage_detail.html'
    context_object_name = 'webdetail'

class Cap(CreateView):
    template_name = 'myapp/cap.html'
    model = Webpage

class ListV(ListView):
    model = Webpage
    context_object_name = 'webname'
    template_name = 'myapp/webpage_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class Base(TemplateView):
    template_name = 'base.html'

class CreateWebpage(CreateView):
    fields =('name','url','topic')
    model = Webpage

    def get_absolute_url(self):
        return reverse("cwp", kwargs={'pk':self.pk})

class Update(UpdateView):
    fields = ('name', 'url')
    model = Webpage

class DeleteV(DeleteView):
    model = Webpage
    success_url = reverse_lazy('myapp:list')
    # context_object_name = 'delview'
#mpclass CoffeePro(TemplateView):
    #model = Topic
   #template_name = 'myapp/coffeepro.html'
    #return render(request,'myapp/coffeepro.html')

myweb/mysite/myapp/templates/myapp/cap.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <link href="https://fonts.googleapis.com/css?family=Merienda" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <title>MYproject</title>
  </head>
  <body>
    <h2>FILL WEBSITE DETAILS BELOW:</h2>
    <div class='container'>
      <form method="post" action="{% url 'myapp:cap' %}">
        {% csrf_token %}
        {{  form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
  </body>
</html>

myweb/mysite/myapp/templates/myapp/coffeepro.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CBVs</title>
  </head>
  <body>
  <p> CLASS BASED VIEWS TEMPLATE INJECTION</p>
  {{ insert_me }}
  </body>
</html>

myweb/mysite/myapp/templates/myapp/webpage_confirm_delete.html
{% extends "index.html" %}
{% block block_body %}
<div class="container">
  <div class="jumbotron">
<form method="post">{% csrf_token %}
    <h1>Delete {{ webpage.name }}?</h1>
    <input  type="submit" class="btn btn-danger" value="delete">
    <a class="btn btn-warning" href="{% url 'myapp:detail' webpage.id  %}">Cancel</a>
</form>
       </div>
</div>
{% endblock %}

myweb/mysite/myapp/templates/myapp/webpage_detail.html
{% extends "index.html" %}
{% block block_body %}
<div class="container">
  <div class="jumbotron">
    <h1>Webpage Details:</h1>
      <h2><li>Name: {{ webdetail.name }}</li></h2>
      <h2><li>Url : {{ webdetail.url }}</li></h2>
      <h2><li>Topic: {{ webdetail.topic }}</li></h2>
      <div class="container">
          <div class="jumbotron">
              <p><a class="btn btn-primary" href="{% url 'myapp:update' webdetail.id %}">Update</a></p>
              <p><a class="btn btn-danger" href="{% url 'myapp:delete' webdetail.id %}">Delete</a></p>
          </div>
      </div>
  </div>
</div>
{% endblock %}

myweb/mysite/myapp/templates/myapp/webpage_form.html
{% extends "index.html" %}
{% block block_body %}
<h1>
    {% if not form.instance.pk %}
    Create Webpage
    {% else %}
    Update Webpage
    {% endif %}
</h1>
<div class="container">
  <div class="jumbotron">
      <form method='post'>
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" class="btn btn-primary" value="Submit">
      </form>
  </div>
</div>
{% endblock %}

myweb/mysite/myapp/templates/myapp/webpage_list.html
{% extends "index.html" %}
{% block title %}Haksite{% endblock %}
{% block block_body %}
<div class="container">
  <div class="jumbotron">
    <h1>Webpage List</h1>
    <ol>
      {% for wp in webname %}
      <h2><li><a href="{% url 'myapp:detail'  wp.id  %}">{{wp.name}}</a></li></h2>
      {% endfor %}
    </ol>
      <h3>Today is {{ now }} Fuck IT!!! Python is damn powerful(*_*) Moses.H</h3>
  </div>
</div>
{% endblock %}

myweb/mysite/templates/base.html
{% load staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Haksite</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">


    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'myapp:thankyou' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'myapp:coffeepro' %}">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'myapp:cap' %}">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>My First Bootstrap Trial Site</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'myapp:pro' %}">Find Out More</a>
          </div>
        </div>
      </div>
    </header>

    <section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">We've got what you need!</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
          </div>
        </div>
      </div>
    </section>

    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">At Your Service</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-gem text-primary mb-3 sr-icon-1"></i>
              <h3 class="mb-3">Sturdy Templates</h3>
              <p class="text-muted mb-0">Our templates are updated regularly so they don't break.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-paper-plane text-primary mb-3 sr-icon-2"></i>
              <h3 class="mb-3">Ready to Ship</h3>
              <p class="text-muted mb-0">You can use this theme as is, or you can make changes!</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-code text-primary mb-3 sr-icon-3"></i>
              <h3 class="mb-3">Up to Date</h3>
              <p class="text-muted mb-0">We update dependencies to keep things fresh.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-heart text-primary mb-3 sr-icon-4"></i>
              <h3 class="mb-3">Made with Love</h3>
              <p class="text-muted mb-0">You have to make your websites with love these days!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="p-0" id="portfolio">
      <div class="container-fluid p-0">
        <div class="row no-gutters popup-gallery">
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/1.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/1.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/2.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/2.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/3.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/3.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/4.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/4.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/5.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/5.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/6.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/6.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>

    <section class="bg-dark text-white">
      <div class="container text-center">
        <h2 class="mb-4">Free Download at Start Bootstrap!</h2>
        <a class="btn btn-light btn-xl sr-button" href="http://startbootstrap.com/template-overviews/creative/">Download Now!</a>
      </div>
    </section>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Let's Get In Touch!</h2>
            <hr class="my-4">
            <p class="mb-5">Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
            <p>+212-680-491-745</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
            <p>
              <a href="mailto:moseshakim23@gmail.com">feedback@haksite.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/creative.min.js' %}"></script>

  </body>

</html>
-->

myweb/mysite/templates/index.html
{% load staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Haksite</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">


    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'myapp:cwp' %}">WepDetails</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'myapp:cwp' %}">CreateWebpage</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'myapp:list' %}">WepList</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block block_body %}

    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>My First Bootstrap Trial Site</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#">Find Out More</a>
          </div>
        </div>
      </div>
    </header>

    <section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">We've got what you need!</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
          </div>
        </div>
      </div>
    </section>

    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">At Your Service</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-gem text-primary mb-3 sr-icon-1"></i>
              <h3 class="mb-3">Sturdy Templates</h3>
              <p class="text-muted mb-0">Our templates are updated regularly so they don't break.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-paper-plane text-primary mb-3 sr-icon-2"></i>
              <h3 class="mb-3">Ready to Ship</h3>
              <p class="text-muted mb-0">You can use this theme as is, or you can make changes!</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-code text-primary mb-3 sr-icon-3"></i>
              <h3 class="mb-3">Up to Date</h3>
              <p class="text-muted mb-0">We update dependencies to keep things fresh.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-heart text-primary mb-3 sr-icon-4"></i>
              <h3 class="mb-3">Made with Love</h3>
              <p class="text-muted mb-0">You have to make your websites with love these days!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="p-0" id="portfolio">
      <div class="container-fluid p-0">
        <div class="row no-gutters popup-gallery">
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/1.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/1.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/2.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/2.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/3.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/3.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/4.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/4.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/5.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/5.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="static/img/portfolio/fullsize/6.jpg">
              <img class="img-fluid" src="static/img/portfolio/thumbnails/6.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>

    <section class="bg-dark text-white">
      <div class="container text-center">
        <h2 class="mb-4">Free Download at Start Bootstrap!</h2>
        <a class="btn btn-light btn-xl sr-button" href="http://startbootstrap.com/template-overviews/creative/">Download Now!</a>
      </div>
    </section>
    {% endblock %}
    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Let's Get In Touch!</h2>
            <hr class="my-4">
            <p class="mb-5">Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
            <p>+212-680-491-745</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
            <p>
              <a href="mailto:moseshakim23@gmail.com">feedback@haksite.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/creative.min.js' %}"></script>

  </body>

</html>